language:
  - ruby

rvm:
  - 2.3.1

install:
  - bundle install --path vendor/bundle

before_script:
  - if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then gem install travisci-bundle-update-pr; travisci-bundle-update-pr 'Yasufumi Moritake' mediba-moritake@mediba.jp; fi
